#!/bin/sh

#### Cleanup if reloading BSPWM ####
killall "sxhkd"
killall "polybar"
killall "feh"
killall "unclutter"
killall "caffeine"
killall "picom"

#### AUTOSTART ####
sxhkd &
polybar main &
feh --bg-fill ~/pictures/Ju5PuBC.jpg &
#feh --bg-center --image-bg "#222222" ~/pictures/ElesisEmpireSword.png &
unclutter --timeout 5 --ignore-scrolling &
caffeine &
numlockx &
picom &
. ~/scripts/mouse.sh &
. ~/scripts/webcam.sh
#dunst

#### MONITORS ####
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  0
bspc config window_gap                    0
bspc config top_padding                   23
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_Screen 0)
#
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a mpv state=pseudo_tiled
bspc rule -a feh state=floating
